name: PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

env:
  CLOUDFLARE_PROJECT_NAME: landingpage
  CLOUDFLARE_BRANCH_NAME: '#${{ github.event.pull_request.number }} / ${{ github.event.pull_request.title }}'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm run lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run Prettier
        run: pnpm run prettier:check

  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    needs: [lint, prettier]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build Project
        run: pnpm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
          if-no-files-found: error
          overwrite: false

  deploy:
    name: Deploy
    if: ${{ github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name }}
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      pull-requests: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy build --project-name="${{ env.CLOUDFLARE_PROJECT_NAME }}" --branch="${{ env.CLOUDFLARE_BRANCH_NAME }}"

      - name: Get Time
        id: get-time
        run: echo "CURRENT_TIME=$(date -u +"%d/%m/%Y - %H:%M:%S")" >> "$GITHUB_OUTPUT"

      - name: Update Preview Comment
        env:
          PREVIEW_LINK: ${{ steps.deploy.outputs.deployment-url }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: cloudflare_preview_message
          message: |
            **PR Preview at ${{ steps.get-time.outputs.CURRENT_TIME }} UTC**
            |                Name                 |                  Preview                 |
            | ----------------------------------- | ---------------------------------------- |
            |  ${{ env.CLOUDFLARE_BRANCH_NAME }}  | [Visit Preview](${{ env.PREVIEW_LINK }}) |
